### ISSUE TITLE
 Feedback on Introduction (3rd priority)

### ISSUE THREAD

**Issue by annielytical** [owensgroup/Robison_Gunrock_Report#4]
[Here is the link to my report PDF.](https://github.com/owensgroup/Robison_MS_Project_Report/blob/c03c8bb72a48636f7408d5447f759b4b1cdf93cf/report.pdf)

Introduction
- Is this too high-level in your opinion?
- Does it provide enough context to understand later sections?

**Comment by jowens** [comment]
The P&P example is charming, but I'm going to suggest that if you pick a real-life example, you pick one that is more complex than a tree (particularly the simple tree that you drew). More to the point, though, if you're going to pick an example, you'd rather pick one that you use to demonstrate a point in your paper. It is unlikely that anyone reading this paper will not know what a graph is, and that's kind of all you're doing with it now. But if you instead use an example that underscores / supports a particular point you're trying to make in the introduction, that's a much better use of an example.  (The fact you switch to a different, abstract example to discuss BFS underscores my concern that the P&P example isn't really doing anything.) (One could imagine an example wrt P&P / literature that attempted to find love triangles or perhaps find characters across different books that are most similar.)

I pretty much tell everyone the exact same advice regarding an introduction: it should have the following 4 things:

1. What is the problem you're solving?
2. Why is the problem interesting? (Your fourth paragraph starts to address this.) 
3. Why is the problem hard and/or unsolved?
4. What are your specific contributions toward solving / making progress on the problem?

In your current intro, it is not clear at all what is the problem you're trying to solve. Neither is it clear what you have actually done. I'd like you to rethink the intro in the context of the above, with the goal that a technical person who is not an expert in our field could read and understand the above. You can work in a lot of what you wrote. But the list above is what I look for in an intro and I hope that your intro can communicate this.

You would do well to write a _thesis_ (soon) that focuses your work. I love this advice: https://web.cs.ucla.edu/~palsberg/shivers.html

**Comment by annielytical** [comment]
Thank you for the feedback on all three sections. I completely see your points and agree with what you've written. I am working now on incorporating the feedback.
