### ISSUE TITLE
Review code contributions and data collected

### ISSUE THREAD

**Issue by annielytical** [owensgroup/Robison_Gunrock_Report#6]
Here is a summary of my code contributions and data collected as requested. I have scheduled time on Tuesday to discuss.

Code contributions:
- Wrote MST algorithm
  - GPU implementation
  - CPU implementation
- Added NVBench benchmarking support for all algorithms
  - This is not designed to work for programs with their own main function. As such, I had to research the NVBench code extensively and reach out to NVIDIA to find a solution
- Implemented performance analysis for BC, BFS, PR, and SSSP
  - This implementation used a runtime variable to turn performance analysis on and off
  - Counters for the metrics were primarily incremented within the lambda functions defined within the individual algorithm hxx files
- Updated graph builder to support CSR and CSC simultaneously and store graph properties
  - Previously both CSC and CSR were supported but could not be used simultaneously because the data structures used pointers without separate storage
- Reworked performance analysis
  - Switched to a compile-time preprocessing variable for the on / off switch
  - Moved metrics collection from algorithm lambda functions into the operator code
  - Support for same four algorithms

Data collected:
- Metrics: Edges visited, vertices visited, MTEPS, search depth, and runtime
- Algorithms: BFS (with performance evaluation on and off) and reverse BFS
- Datasets: Suitesparse datasets used for the original Gunrock's performance evaluation
- I could collect the same data for BC, PR, and SSSP

**Comment by jowens** [comment]
Discussed in indiv meeting morning of Dec 5.
